### ISSUE TITLE
ModuleNotFoundError: No module named 'KEYS'

### ISSUE THREAD

**Issue by EMSWAN77** [TIANYUZHOU/KaoYan-InfoWeb_CS_Backend#2]
![image](https://user-images.githubusercontent.com/54491143/210520463-1ced920e-e9fd-4f6a-84c8-cf82a50570d4.png)
运行到python manage.py makemigrations这步报错

**Comment by TIANYUZHOU** [comment]
这个是阿里云短信接口的密钥，你可以自己申请一个放到"KEYS"文件夹的“my_keys.py”中或者自己建另外一个文件放密钥再import。
“my_keys.py”内容像这样：
![image](https://user-images.githubusercontent.com/53137506/210521707-e78320e6-b165-40df-bd3a-99b1950c736a.png)

**Comment by EMSWAN77** [comment]
好的，非常感谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月4日(星期三) 下午5:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TIANYUZHOU/KaoYan-InfoWeb_CS_Backend] ModuleNotFoundError: No module named &#39;KEYS&#39; (Issue #2)





 
这个是阿里云短信接口的密钥，你可以自己申请一个放到"KEYS"文件夹的“my_keys.py”中或者自己建另外一个文件放密钥再import。
 “my_keys.py”内容像这样：

**Comment by EMSWAN77** [comment]
完了，手滑把那个关掉了，其他的回复没有看到，麻烦再说一下/(ㄒoㄒ)/~~

**Comment by TIANYUZHOU** [comment]
> 完了，手滑把那个关掉了，其他的回复没有看到，麻烦再说一下/(ㄒoㄒ)/~~

你点close的issue可以查看记录的

**Comment by EMSWAN77** [comment]
关于短信接口写法：我目前就是git的这个项目，除了一些mysql和腾讯云的配置，其他都还没动过，那个腾讯云配置真不知道问题出哪儿了，都是按照api文档配置的

**Comment by TIANYUZHOU** [comment]
> 关于短信接口写法：我目前就是git的这个项目，除了一些mysql和腾讯云的配置，其他都还没动过，那个腾讯云配置真不知道问题出哪儿了，都是按照api文档配置的

那个报错是腾讯云短信那边给的，是没有找到短信模板(这个是自己编写的)，你只能去看看腾讯云那里你的短信模板是否配置正确。

**Comment by EMSWAN77** [comment]
![image](https://user-images.githubusercontent.com/54491143/211133624-d80f82a9-6248-468c-8209-2f420f884419.png)
这是模板内容，我去搜那个报错也有人说是参数问题，我这里就是一个参数，我在参数三种都试过，“5”、“”、“1”，都还是不行，我的模板的ID也是没问题的

**Comment by EMSWAN77** [comment]
关于那个短信验证码的问题，之前至少还是请求失败
![image](https://user-images.githubusercontent.com/54491143/211144250-99cd8f35-fe96-453b-8f01-6ff3f1de3eed.png)
现在就是也不弹窗报错，就是没有动静了
![image](https://user-images.githubusercontent.com/54491143/211144311-7c817098-dd25-40df-92b7-673d1d01318c.png)
我问了一下腾讯云的客服，他说我的模板里面只有一个参数，你项目原来的短信模板是不是有两个参数
![image](https://user-images.githubusercontent.com/54491143/211144320-0e06ae73-8e38-46ac-b60c-db1212045753.png)

**Comment by EMSWAN77** [comment]
> 关于那个短信验证码的问题，之前至少还是请求失败 ![image](https://user-images.githubusercontent.com/54491143/211144250-99cd8f35-fe96-453b-8f01-6ff3f1de3eed.png) 现在就是也不弹窗报错，就是没有动静了 ![image](https://user-images.githubusercontent.com/54491143/211144311-7c817098-dd25-40df-92b7-673d1d01318c.png) 我问了一下腾讯云的客服，他说我的模板里面只有一个参数，你项目原来的短信模板是不是有两个参数 ![image](https://user-images.githubusercontent.com/54491143/211144320-0e06ae73-8e38-46ac-b60c-db1212045753.png)

重新git项目 部署后，终于成功了（感人）。顺便再问一下，源项目是爬虫的研招网的数据然后存在数据库么？（因为我看到有个历年复试线，这个研招网好像没有，这个复试线分数是怎么搞的呢）
![image](https://user-images.githubusercontent.com/54491143/211178070-7630f2b8-8c40-48c9-a323-f27779fe9f97.png)

**Comment by sweet12321** [comment]
> 关于那个短信验证码的问题，之前至少还是请求失败 ![image](https://user-images.githubusercontent.com/54491143/211144250-99cd8f35-fe96-453b-8f01-6ff3f1de3eed.png) 现在就是也不弹窗报错，就是没有动静了 ![image](https://user-images.githubusercontent.com/54491143/211144311-7c817098-dd25-40df-92b7-673d1d01318c.png) 我问了一下腾讯云的客服，他说我的模板里面只有一个参数，你项目原来的短信模板是不是有两个参数 ![image](https://user-images.githubusercontent.com/54491143/211144320-0e06ae73-8e38-46ac-b60c-db1212045753.png)

你后来是怎么解决的，我也遇到了同意的问题

**Comment by TIANYUZHOU** [comment]
> > 关于那个短信验证码的问题，之前至少还是请求失败 ![image](https://user-images.githubusercontent.com/54491143/211144250-99cd8f35-fe96-453b-8f01-6ff3f1de3eed.png) 现在就是也不弹窗报错，就是没有动静了 ![image](https://user-images.githubusercontent.com/54491143/211144311-7c817098-dd25-40df-92b7-673d1d01318c.png) 我问了一下腾讯云的客服，他说我的模板里面只有一个参数，你项目原来的短信模板是不是有两个参数 ![image](https://user-images.githubusercontent.com/54491143/211144320-0e06ae73-8e38-46ac-b60c-db1212045753.png)
> 
> 你后来是怎么解决的，我也遇到了同意的问题

![image](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/53137506/36e8a770-95c3-424f-9df5-64bd0e7e8a0b)
我的短信模板
