### ISSUE TITLE
启动项目后点开是api root，启动失败

### ISSUE THREAD

**Issue by EMSWAN77** [TIANYUZHOU/KaoYan-InfoWeb_CS_Backend#3]
启动项目后点开是api root，页面如下：
![image](https://user-images.githubusercontent.com/54491143/210702876-bc603ef5-3c34-4367-8dd5-4aa407af7d95.png)
不知道是不是我key放的位置有误？应该放在什么位置呢？以下是我key放置的位置
![image](https://user-images.githubusercontent.com/54491143/210702969-b97aeb9f-a59d-467a-b386-bcea600755b0.png)
（新手上项目，问题可能有点多 麻烦了）

**Comment by TIANYUZHOU** [comment]
跟路径是没有配置任何接口的，你可以在“urls.py”里面看到注册了哪些路由，然后以“/api/xxx”，比如：“api/schools”的格式进行请求。

**Comment by TIANYUZHOU** [comment]
如果是新手的话，建议先熟悉一下django的项目结构和路由逻辑。

**Comment by EMSWAN77** [comment]
好的，谢谢了！那我这个启动失败是为什么啊？

**Comment by TIANYUZHOU** [comment]
> 好的，谢谢了！那我这个启动失败是为什么啊？

1.如果能够访问路由，那就说明项目是启动成功的。
2.KEYS可以放在任何地方，只要你import时的路径能找到就行。
3.源项目是放在项目根目录的：
![image](https://user-images.githubusercontent.com/53137506/210705840-b160c4ab-060f-4bc2-b23c-b3a33eb72140.png)

**Comment by EMSWAN77** [comment]
现在前端部分启动成功，但是注册的时候收不到验证码呢，我就是用我api绑定的那个手机号，我去阿里云查看了没有发送记录呢。后端启动页面，就是最开始我发的那个api root的截图，这样是正常启动页面么？

**Comment by TIANYUZHOU** [comment]
> 现在前端部分启动成功，但是注册的时候收不到验证码呢，我就是用我api绑定的那个手机号，我去阿里云查看了没有发送记录呢。后端启动页面，就是最开始我发的那个api root的截图，这样是正常启动页面么？

这得查看你的后端项目服务启动地址，前端项目注册发送请求的地址必须和后端项目启动的ip以及端口号匹配，当然你可以修改：
![image](https://user-images.githubusercontent.com/53137506/210709407-cd15dd8b-030a-42de-a53c-a08a5efb89cf.png)
[https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS/blob/master/src/components/header/RegisteAndLogin/RegisteAndLogin.vue](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS/blob/master/src/components/header/RegisteAndLogin/RegisteAndLogin.vue)

**Comment by TIANYUZHOU** [comment]
在使用前端前，你可以加上你的手机号直接访问这个接口，进行短信发送测试。（注意改成你的启动地址和端口）
![image](https://user-images.githubusercontent.com/53137506/210710141-b893a75b-be7e-430c-97b5-eb4d48614243.png)

**Comment by EMSWAN77** [comment]
非常感谢！我试试

**Comment by EMSWAN77** [comment]
您好，以下是我的后端启动，端口是8000：
![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png)
以下是前端启动，端口是8080，但是代码里是8000：
![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png)
我在阿里云控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢

**Comment by EMSWAN77** [comment]
对哦 我刚查看了一下数据库，里面的内容都是空的呢（已执行python manage.py migrate）
![image](https://user-images.githubusercontent.com/54491143/210925494-1d8f883c-38e0-4847-8036-18f865a9955b.png)

**Comment by TIANYUZHOU** [comment]
> 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在阿里云控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢

仔细看报错，你的接口密钥不对。

**Comment by TIANYUZHOU** [comment]
> 对哦 我刚查看了一下数据库，里面的内容都是空的呢（已执行python manage.py migrate） ![image](https://user-images.githubusercontent.com/54491143/210925494-1d8f883c-38e0-4847-8036-18f865a9955b.png)

python manage.py migrate 只是将定义的表和字段生成对应的数据库表，不会有任何数据。具体的院校数据需要爬取并导入数据库，或者创建一个超级用户后在"admin/"后台入口手动添加。

**Comment by EMSWAN77** [comment]
> 对哦 我刚查看了一下数据库，里面的内容都是空的呢（已执行python manage.py migrate） ![image](https://user-images.githubusercontent.com/54491143/210925494-1d8f883c-38e0-4847-8036-18f865a9955b.png)

哦哦，是这样，麻烦了

**Comment by EMSWAN77** [comment]
> > 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在阿里云控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢
> 
> 仔细看报错，你的接口密钥不对。
再看了一下代码，好家伙，原来是腾讯云的短信服务。十分感谢

**Comment by TIANYUZHOU** [comment]
> > > 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在阿里云控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢
> > 
> > 仔细看报错，你的接口密钥不对。
> 再看了一下代码，好家伙，原来是腾讯云的短信服务。十分感谢

😂👌

**Comment by EMSWAN77** [comment]
> > > > 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在阿里云控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢
> > > 
> > > 
> > > 仔细看报错，你的接口密钥不对。
> > > 再看了一下代码，好家伙，原来是腾讯云的短信服务。十分感谢
> 
> 😂👌

可是我看了一眼，腾讯云申请：
![image](https://user-images.githubusercontent.com/54491143/211000600-9611328f-235c-4c71-b600-bb6ec488c017.png)
个人使用怎么办啊？

**Comment by TIANYUZHOU** [comment]
> > > > > 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在阿里云控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢
> > > > 
> > > > 
> > > > 仔细看报错，你的接口密钥不对。
> > > > 再看了一下代码，好家伙，原来是腾讯云的短信服务。十分感谢
> > 
> > 😂👌
> 
> 可是我看了一眼，腾讯云申请：
> ![image](https://user-images.githubusercontent.com/54491143/211000600-9611328f-235c-4c71-b600-bb6ec488c017.png)
> 个人使用怎么办啊？
> 

你可以把接口改成阿里云的。

**Comment by EMSWAN77** [comment]
> 

okk 其他地方的代码不用动吧？

**Comment by TIANYUZHOU** [comment]
> > 
> 
> okk 其他地方的代码不用动吧？

嗯

**Comment by EMSWAN77** [comment]
为什么后台运行一点开是如下的api的那个url呢？
![image](https://user-images.githubusercontent.com/54491143/211128758-f25ef305-afa7-463d-9e0e-5d9bbb7ffb61.png)
我是手动在后面加了/admin才进入以下界面的
![image](https://user-images.githubusercontent.com/54491143/211128751-886b7f6b-c7aa-4d8a-8cf0-f29f372e05fc.png)
顺便问一下，我直接在数据库创建的用户还是没办法登录后台系统呢
![image](https://user-images.githubusercontent.com/54491143/211128810-b349aec3-1387-4cee-8740-c56795d09683.png)
前台登录也是在这个user_user表里面么

**Comment by EMSWAN77** [comment]
现在注册一直都是弹出：request content does not match the template content
![image](https://user-images.githubusercontent.com/54491143/211132615-c11075d7-d337-43f3-b764-0aa69444fe61.png)
然后我发现验证码传到了终端，但是点击提交（1.第一次用的手机号是我在数据库直接创建的账号的手机号，但是这个创建的用户无论是前台还是后台都无法登录2.第二次用另一个手机号点击提交后就没有反应了）
![image](https://user-images.githubusercontent.com/54491143/211132693-b09b3c87-91d2-4a0b-8e4f-053b13f0f755.png)
request content does not match the template content这个报错我不知道是不是我参数那里没有写对（没能理解到意思），参数部分在上图用红色箭头标出了

**Comment by TIANYUZHOU** [comment]
> 现在注册一直都是弹出：request content does not match the template content
> ![image](https://user-images.githubusercontent.com/54491143/211132615-c11075d7-d337-43f3-b764-0aa69444fe61.png)
> 然后我发现验证码传到了终端，但是点击提交（1.第一次用的手机号是我在数据库直接创建的账号的手机号，但是这个创建的用户无论是前台还是后台都无法登录2.第二次用另一个手机号点击提交后就没有反应了）
> ![image](https://user-images.githubusercontent.com/54491143/211132693-b09b3c87-91d2-4a0b-8e4f-053b13f0f755.png)
> request content does not match the template content这个报错我不知道是不是我参数那里没有写对（没能理解到意思），参数部分在上图用红色箭头标出了

这很明显是你短信接口没配置正确，如果你用的是阿里云的话建议仔细看看相应教程。

**Comment by TIANYUZHOU** [comment]
> 为什么后台运行一点开是如下的api的那个url呢？
> ![image](https://user-images.githubusercontent.com/54491143/211128758-f25ef305-afa7-463d-9e0e-5d9bbb7ffb61.png)
> 我是手动在后面加了/admin才进入以下界面的
> ![image](https://user-images.githubusercontent.com/54491143/211128751-886b7f6b-c7aa-4d8a-8cf0-f29f372e05fc.png)
> 顺便问一下，我直接在数据库创建的用户还是没办法登录后台系统呢
> ![image](https://user-images.githubusercontent.com/54491143/211128810-b349aec3-1387-4cee-8740-c56795d09683.png)
> 前台登录也是在这个user_user表里面么

不能在数据库直接插入用户，因为存储的密码是哈希过后的，直接插入是明文。并且直接插入的用户不会有后台权限。超级用户需要使用Django命令创建，具体命令建议自行搜索一下。

**Comment by TIANYUZHOU** [comment]
至于根路径问题，如果你不想通过“/admin”进入管理页面而是想通过根路径进去，可以自行进行路由重定向配置。（路由配置在“urls.py”）

**Comment by TIANYUZHOU** [comment]
> 现在注册一直都是弹出：request content does not match the template content
> ![image](https://user-images.githubusercontent.com/54491143/211132615-c11075d7-d337-43f3-b764-0aa69444fe61.png)
> 然后我发现验证码传到了终端，但是点击提交（1.第一次用的手机号是我在数据库直接创建的账号的手机号，但是这个创建的用户无论是前台还是后台都无法登录2.第二次用另一个手机号点击提交后就没有反应了）
> ![image](https://user-images.githubusercontent.com/54491143/211132693-b09b3c87-91d2-4a0b-8e4f-053b13f0f755.png)
> request content does not match the template content这个报错我不知道是不是我参数那里没有写对（没能理解到意思），参数部分在上图用红色箭头标出了

检查一下你的短信接口写法是有否将收到的验证码进行缓存，如果没有。那么后台是无法读取进行验证的（可以参照项目原来的短信接口逻辑）

**Comment by EMSWAN77** [comment]
> > 现在注册一直都是弹出：request content does not match the template content
> > ![image](https://user-images.githubusercontent.com/54491143/211132615-c11075d7-d337-43f3-b764-0aa69444fe61.png)
> > 然后我发现验证码传到了终端，但是点击提交（1.第一次用的手机号是我在数据库直接创建的账号的手机号，但是这个创建的用户无论是前台还是后台都无法登录2.第二次用另一个手机号点击提交后就没有反应了）
> > ![image](https://user-images.githubusercontent.com/54491143/211132693-b09b3c87-91d2-4a0b-8e4f-053b13f0f755.png)
> > request content does not match the template content这个报错我不知道是不是我参数那里没有写对（没能理解到意思），参数部分在上图用红色箭头标出了
> 
> 这很明显是你短信接口没配置正确，如果你用的是阿里云的话建议仔细看看相应教程。

我现在就用的腾讯云，就按照你代码里面做相应的配置的
![image](https://user-images.githubusercontent.com/54491143/211133179-d198c815-bdd2-4cb6-82fb-4d0421cc723d.png)

**Comment by EMSWAN77** [comment]
> 
但是url配置的就是直接进admin，但是运行后打开127.0.0.1：8000就是那个api的页面
![image](https://user-images.githubusercontent.com/54491143/211133269-9cb1761d-cd21-43b8-acb9-07d6913c1e23.png)

**Comment by TIANYUZHOU** [comment]
> > 
> 但是url配置的就是直接进admin，但是运行后打开127.0.0.1：8000就是那个api的页面
> ![image](https://user-images.githubusercontent.com/54491143/211133269-9cb1761d-cd21-43b8-acb9-07d6913c1e23.png)
> 

因为项目默认启动就是根路径“/”，你完全可以把“/admin”改成“/”。

**Comment by EMSWAN77** [comment]
![image](https://user-images.githubusercontent.com/54491143/211133738-efe22651-4729-422d-b374-4fe5efb9089d.png)
欸 还是不行呢

**Comment by EMSWAN77** [comment]
> > > 
> > 
> > 
> > 但是url配置的就是直接进admin，但是运行后打开127.0.0.1：8000就是那个api的页面
> > ![image](https://user-images.githubusercontent.com/54491143/211133269-9cb1761d-cd21-43b8-acb9-07d6913c1e23.png)
> 
> 因为项目默认启动就是根路径“/”，你完全可以把“/admin”改成“/”。
终端：
![image](https://user-images.githubusercontent.com/54491143/211133829-e8116c2b-58b1-4202-8d65-094020f969bb.png)

**Comment by TIANYUZHOU** [comment]
> > > > 
> > > 
> > > 
> > > 但是url配置的就是直接进admin，但是运行后打开127.0.0.1：8000就是那个api的页面
> > > ![image](https://user-images.githubusercontent.com/54491143/211133269-9cb1761d-cd21-43b8-acb9-07d6913c1e23.png)
> > 
> > 因为项目默认启动就是根路径“/”，你完全可以把“/admin”改成“/”。
> 终端：
> ![image](https://user-images.githubusercontent.com/54491143/211133829-e8116c2b-58b1-4202-8d65-094020f969bb.png)
> 
[Django路由重定向](https://blog.csdn.net/qq_41475583/article/details/105687852?utm_source=app&app_version=5.1.1&code=app_1562916241&uLinkId=usr1mkqgl919blen)
或者将首页设置成后台入口

**Comment by EMSWAN77** [comment]
> 

改成了“”就好了

**Comment by sweet12321** [comment]
> > > > > > 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在阿里云控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢
> > > > > 
> > > > > 
> > > > > 仔细看报错，你的接口密钥不对。
> > > > > 再看了一下代码，好家伙，原来是腾讯云的短信服务。十分感谢
> > > 
> > > 
> > > 😂👌
> > 
> > 
> > 可是我看了一眼，腾讯云申请：
> > ![image](https://user-images.githubusercontent.com/54491143/211000600-9611328f-235c-4c71-b600-bb6ec488c017.png)
> > 个人使用怎么办啊？
> 
> 你可以把接口改成阿里云的。

大佬，如果改成阿里云的应该怎么改啊，我改的一直报错

**Comment by TIANYUZHOU** [comment]
> > > > > > > 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在阿里云控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢
> > > > > > 
> > > > > > 
> > > > > > 仔细看报错，你的接口密钥不对。
> > > > > > 再看了一下代码，好家伙，原来是腾讯云的短信服务。十分感谢
> > > > 
> > > > 
> > > > 😂👌
> > > 
> > > 
> > > 可是我看了一眼，腾讯云申请：
> > > ![image](https://user-images.githubusercontent.com/54491143/211000600-9611328f-235c-4c71-b600-bb6ec488c017.png)
> > > 个人使用怎么办啊？
> > 
> > 
> > 你可以把接口改成阿里云的。
> 
> 大佬，如果改成阿里云的应该怎么改啊，我改的一直报错

去看阿里云短信的开发文档

**Comment by sweet12321** [comment]
> > > 现在注册一直都是弹出：request content does not match the template content
> > > ![image](https://user-images.githubusercontent.com/54491143/211132615-c11075d7-d337-43f3-b764-0aa69444fe61.png)
> > > 然后我发现验证码传到了终端，但是点击提交（1.第一次用的手机号是我在数据库直接创建的账号的手机号，但是这个创建的用户无论是前台还是后台都无法登录2.第二次用另一个手机号点击提交后就没有反应了）
> > > ![image](https://user-images.githubusercontent.com/54491143/211132693-b09b3c87-91d2-4a0b-8e4f-053b13f0f755.png)
> > > request content does not match the template content这个报错我不知道是不是我参数那里没有写对（没能理解到意思），参数部分在上图用红色箭头标出了
> > 
> > 
> > 这很明显是你短信接口没配置正确，如果你用的是阿里云的话建议仔细看看相应教程。
> 
> 我现在就用的腾讯云，就按照你代码里面做相应的配置的 ![image](https://user-images.githubusercontent.com/54491143/211133179-d198c815-bdd2-4cb6-82fb-4d0421cc723d.png)

短信接口方面是不是只用修改上面图片中的那四处，我修改了，为什么手机还是接收不到验证码

**Comment by sweet12321** [comment]
后台还这样标红

**Comment by sweet12321** [comment]
![77](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/19b14e13-d881-4792-b827-057bb79ba05f)

**Comment by sweet12321** [comment]
![77](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/98474885-e735-4d6e-998b-0d5a3e4a8f3e)

**Comment by TIANYUZHOU** [comment]
> ![77](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/98474885-e735-4d6e-998b-0d5a3e4a8f3e)
> 

可能现在的腾讯云短信接口代码已经变了，建议看它短信接口的文档示例。

**Comment by sweet12321** [comment]
> 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在腾讯控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢

我也遇到了同样的问题

**Comment by sweet12321** [comment]
前端是这样的
![2222](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/15b5e817-0988-480d-8699-46773c9845ff)

**Comment by TIANYUZHOU** [comment]
> 前端是这样的
> ![2222](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/15b5e817-0988-480d-8699-46773c9845ff)
> 

后端启动的时候可以指定端口

**Comment by sweet12321** [comment]
意思是他们的启动后的端口都要是一样的吗，就像这样
![后](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/540d4bff-689b-4cf7-b8f5-ab64eedaaa15)
![前端](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/9d71417a-7164-4493-ac50-d9d675579d23)

**Comment by TIANYUZHOU** [comment]
> 意思是他们的启动后的端口都要是一样的吗，就像这样
> ![后](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/540d4bff-689b-4cf7-b8f5-ab64eedaaa15)
> ![前端](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/assets/161267611/9d71417a-7164-4493-ac50-d9d675579d23)
> 

不是，前端不用动，把后端改成8000就好了

**Comment by TIANYUZHOU** [comment]
> > 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在腾讯控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢
> 
> 我也遇到了同样的问题
> 

你这个报错，是已经收到验证码了和端口没关系

**Comment by TIANYUZHOU** [comment]
> > > 您好，以下是我的后端启动，端口是8000： ![image](https://user-images.githubusercontent.com/54491143/210922953-e9bcb2b8-6355-4703-9411-e858353d9f60.png) 以下是前端启动，端口是8080，但是代码里是8000： ![image](https://user-images.githubusercontent.com/54491143/210923108-a7df9f55-5d07-4313-9ac7-ce810c7db0ce.png) 我在腾讯控制台调用API短信测试是ok的，但是项目还是没办法收到短信呢
> > 
> > 我也遇到了同样的问题
> > 
> 
> 你这个报错，是已经收到验证码了和端口没关系

看报错，是腾讯云短信接口抛的错
