### ISSUE TITLE
源项目数据库的内容是爬虫的那个网站呢？

### ISSUE THREAD

**Issue by EMSWAN77** [TIANYUZHOU/KaoYan-InfoWeb_CS_Backend#4]
（研招网好像没有历年复试线）可否分享一下爬虫的源码呢
![image](https://user-images.githubusercontent.com/54491143/211241044-1d399f74-8d7e-4cbc-89ec-29bc7cea641e.png)

**Comment by TIANYUZHOU** [comment]
> （研招网好像没有历年复试线）可否分享一下爬虫的源码呢
> ![image](https://user-images.githubusercontent.com/54491143/211241044-1d399f74-8d7e-4cbc-89ec-29bc7cea641e.png)
> 

现在研招网的网页结构已经更新了，建议自己重写爬虫。关于复试线的问题，由于各个学校没有统一的公布平台，目前只能从第三方平台爬取整理好的分数或者自行后台手动加入。

**Comment by EMSWAN77** [comment]
> 

好的 非常感谢

**Comment by TIANYUZHOU** [comment]
> > 
> 
> 好的 非常感谢

不谢👌

**Comment by sweet12321** [comment]
> > （研招网好像没有历年复试线）可否分享一下爬虫的源码呢
> > ![image](https://user-images.githubusercontent.com/54491143/211241044-1d399f74-8d7e-4cbc-89ec-29bc7cea641e.png)
> 
> 现在研招网的网页结构已经更新了，建议自己重写爬虫。关于复试线的问题，由于各个学校没有统一的公布平台，目前只能从第三方平台爬取整理好的分数或者自行后台手动加入。

大佬，那意思是目前这个项目里面没有爬虫，爬虫方面的代码得自己写吗

**Comment by sweet12321** [comment]
> > （研招网好像没有历年复试线）可否分享一下爬虫的源码呢
> > ![image](https://user-images.githubusercontent.com/54491143/211241044-1d399f74-8d7e-4cbc-89ec-29bc7cea641e.png)
> 
> 现在研招网的网页结构已经更新了，建议自己重写爬虫。关于复试线的问题，由于各个学校没有统一的公布平台，目前只能从第三方平台爬取整理好的分数或者自行后台手动加入。

大佬，那意思是目前这个项目里面没有爬虫，爬虫方面的代码得自己写吗

**Comment by TIANYUZHOU** [comment]
是的

**Comment by TIANYUZHOU** [comment]
> > > （研招网好像没有历年复试线）可否分享一下爬虫的源码呢
> > > ![image](https://user-images.githubusercontent.com/54491143/211241044-1d399f74-8d7e-4cbc-89ec-29bc7cea641e.png)
> > 
> > 现在研招网的网页结构已经更新了，建议自己重写爬虫。关于复试线的问题，由于各个学校没有统一的公布平台，目前只能从第三方平台爬取整理好的分数或者自行后台手动加入。
> 
> 大佬，那意思是目前这个项目里面没有爬虫，爬虫方面的代码得自己写吗

是的

**Comment by sweet12321** [comment]
> > > > （研招网好像没有历年复试线）可否分享一下爬虫的源码呢
> > > > ![image](https://user-images.githubusercontent.com/54491143/211241044-1d399f74-8d7e-4cbc-89ec-29bc7cea641e.png)
> > > 
> > > 
> > > 现在研招网的网页结构已经更新了，建议自己重写爬虫。关于复试线的问题，由于各个学校没有统一的公布平台，目前只能从第三方平台爬取整理好的分数或者自行后台手动加入。
> > 
> > 
> > 大佬，那意思是目前这个项目里面没有爬虫，爬虫方面的代码得自己写吗
> 
> 是的

那可否把爬虫部分代码分享一下，我参考着重新写一下，这部分不是很懂，正在学习
