### ISSUE TITLE
分数线的输入格式是怎么样的呢？

### ISSUE THREAD

**Issue by EMSWAN77** [TIANYUZHOU/KaoYan-InfoWeb_CS_Backend#5]
我看前端代码是用逗号分隔开的
![image](https://user-images.githubusercontent.com/54491143/211465583-aded03ea-71ef-4374-9bd5-fdbf923a605c.png)
我在后台系统里面就这样写的
![image](https://user-images.githubusercontent.com/54491143/211465616-967a810b-f472-4ccc-9d11-e546160a311f.png)
但是前端页面就没法显示：
![image](https://user-images.githubusercontent.com/54491143/211465664-4884316c-ed18-44b5-ab80-743b536a32bb.png)
但是如果我只输入一个分数 就可以显示再2018年那个位置的分数

**Comment by TIANYUZHOU** [comment]
> 我看前端代码是用逗号分隔开的
> ![image](https://user-images.githubusercontent.com/54491143/211465583-aded03ea-71ef-4374-9bd5-fdbf923a605c.png)
> 我在后台系统里面就这样写的
> ![image](https://user-images.githubusercontent.com/54491143/211465616-967a810b-f472-4ccc-9d11-e546160a311f.png)
> 但是前端页面就没法显示：
> ![image](https://user-images.githubusercontent.com/54491143/211465664-4884316c-ed18-44b5-ab80-743b536a32bb.png)
> 但是如果我只输入一个分数 就可以显示再2018年那个位置的分数

以“|”隔开

**Comment by EMSWAN77** [comment]
好的 麻烦了
