### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by EMSWAN77** [TIANYUZHOU/KaoYan-InfoWeb_CS_Backend#6]
之前有一次也是这样，突然前台就请求不了数据库的内容了，我重新git部署项目又可以了，以为是之前改到什么然后出现的问题，部署后除了基本配置都没改过（还在学习django和vue，边学边看项目），结果今天一启动就403了
![image](https://user-images.githubusercontent.com/54491143/212034086-e3f44fc5-45a4-4955-97fe-410fb738e3ee.png)
终端报错如下：
![image](https://user-images.githubusercontent.com/54491143/212034731-994dcbf8-c90f-434a-a663-b5ed5e8cc454.png)
有尝试网上的解决办法还是不行呢
![image](https://user-images.githubusercontent.com/54491143/212034847-3aefef40-b31e-4195-b987-eb4a4f0b5622.png)

**Comment by TIANYUZHOU** [comment]
> 之前有一次也是这样，突然前台就请求不了数据库的内容了，我重新git部署项目又可以了，以为是之前改到什么然后出现的问题，部署后除了基本配置都没改过（还在学习django和vue，边学边看项目），结果今天一启动就403了
> ![image](https://user-images.githubusercontent.com/54491143/212034086-e3f44fc5-45a4-4955-97fe-410fb738e3ee.png)
> 终端报错如下：
> ![image](https://user-images.githubusercontent.com/54491143/212034731-994dcbf8-c90f-434a-a663-b5ed5e8cc454.png)
> 有尝试网上的解决办法还是不行呢
> ![image](https://user-images.githubusercontent.com/54491143/212034847-3aefef40-b31e-4195-b987-eb4a4f0b5622.png)
> 

Django indeed started enforcing an origin check for CSRF starting in v4.0: https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf

Setting the following fixed:

```python
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:xxxx",
    "http://127.0.0.1:xxxx",
]
```

**Comment by TIANYUZHOU** [comment]
> > 之前有一次也是这样，突然前台就请求不了数据库的内容了，我重新git部署项目又可以了，以为是之前改到什么然后出现的问题，部署后除了基本配置都没改过（还在学习django和vue，边学边看项目），结果今天一启动就403了
> > ![image](https://user-images.githubusercontent.com/54491143/212034086-e3f44fc5-45a4-4955-97fe-410fb738e3ee.png)
> > 终端报错如下：
> > ![image](https://user-images.githubusercontent.com/54491143/212034731-994dcbf8-c90f-434a-a663-b5ed5e8cc454.png)
> > 有尝试网上的解决办法还是不行呢
> > ![image](https://user-images.githubusercontent.com/54491143/212034847-3aefef40-b31e-4195-b987-eb4a4f0b5622.png)
> > 
> 
> Django indeed started enforcing an origin check for CSRF starting in v4.0: https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf
> 
> Setting the following fixed:
> 
> ```python
> CSRF_TRUSTED_ORIGINS = [
>     "http://localhost:xxxx",
>     "http://127.0.0.1:xxxx",
> ]
> ```

“xxxx”是你用的端口

**Comment by EMSWAN77** [comment]
好的，十分感谢！

**Comment by EMSWAN77** [comment]
> 

欸，还是不行呢（是再Settings里添加以上代码吧？）
![image](https://user-images.githubusercontent.com/54491143/212047497-f13233fe-bcdf-47b8-b49d-8155d4070003.png)

**Comment by EMSWAN77** [comment]
今天早上再次重新部署项目，开始两次运行都还是正常的，然后我开始在数据库添加内容后，就开始前端请求不到数据了，网页显示不出内容了，之前出现403的报错的时候，就是我发现网页请求不到数据，我退出登录，重新登陆时提交表单报的错
![image](https://user-images.githubusercontent.com/54491143/212237287-70061316-3941-4dec-ad26-6b4980d50ce8.png)
目前状态的终端：
![image](https://user-images.githubusercontent.com/54491143/212237494-5d463890-093a-4706-91f4-6ff776df56ca.png)

**Comment by EMSWAN77** [comment]
最近又突然出现了这个问题，您之前方法也采用了，网上注释掉'django.middleware.csrf.CsrfViewMiddleware'的方法也不行
![Uploading image.png…]()
