### ISSUE TITLE
No module named 'corsheaders'

### ISSUE THREAD

**Issue by zhuzzzzzz** [TIANYUZHOU/KaoYan-InfoWeb_CS_Backend#8]
![image](https://user-images.githubusercontent.com/57058943/232365499-25c495f3-83aa-4fcd-9cfc-37c535daca3e.png)

你好，请问一下makemigrations的适合报这个错是什么问题啊

**Comment by TIANYUZHOU** [comment]
`pip install django-cors-headers `

**Comment by zhuzzzzzz** [comment]
![image](https://user-images.githubusercontent.com/57058943/232366665-dab3fcfc-d7d4-4122-a939-e1ef4d05a8c0.png)


谢谢！还有这个......

**Comment by TIANYUZHOU** [comment]
issue里面有提[https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/issues/2](https://github.com/TIANYUZHOU/KaoYan-InfoWeb_CS_Backend/issues/2) 注意是**腾讯云**的短信接口KEY

**Comment by zhuzzzzzz** [comment]
![image](https://user-images.githubusercontent.com/57058943/232369149-fc3716fa-9323-46ce-b56f-fba8e4f2f053.png)
哦好的，我以为是阿里云，刚去搞了个阿里云的...
另外这个是什么问题呀？simpleui我是直接pip install simpleui装上去的
